### ISSUE TITLE
Fixing Template Docs URL

### ISSUE THREAD

**Issue by rpolnx** [gabriel-pinheiro/mocko#14]
# Description
Wrong redirect on templating docs. 
Path:
- https://mocko.dev/
- By clicking on the phrase link "Create dynamic mocks using Handlebars (more here)" redirects to private cluster domain.

# How to Fix
Changing href from "/templating" to "https://mocko.dev/templating/"

# Image
![image](https://user-images.githubusercontent.com/19880501/107310444-3220fe00-6a6b-11eb-86dc-ad1a64e69228.png)

![image](https://user-images.githubusercontent.com/19880501/107310799-e4f15c00-6a6b-11eb-8ee1-c2e06beecbdb.png)

**Comment by gabriel-pinheiro** [comment]
Fixed in the latest update, thanks for reporting 😄
